[build]

  publish = "dist/tourexpertsmean/browser"
 command = "ng build --configuration=production"

[[plugins]]
  package = "@netlify/angular-runtime"

  [[redirects]]
from = "/*"
to = "/index.html"
status = 200 